### ISSUE TITLE
Mismatch between AlphaPose generated keypoints format and retiming code expected format

### ISSUE THREAD

**Issue by Hugstar** [google/retiming#2]
Hi. I'm interested in running inference on my own video.
I've followed the instructions and got stuck at step 3 which specifies: "Run AlphaPose and Pose Tracking".
I've ran AlphaPose with tracking (knowing the exact tracking configuration command you have used would be very useful by the way).

None of the data formats which have been specified in the official [AlphaPose output formats](https://github.com/MVIG-SJTU/AlphaPose/blob/master/docs/output.md) is the one your code expects.

Your code expects keypoints in format [[x1,y1,1], [x2,y2,1] ....], but none of the output formats in the document I've shared supports that. 

Could you please share how to do the conversion? Or perhaps a more detailed process of how to generate keypoints in this format?

**Comment by erikalu** [comment]
Hi, sorry for the confusion. It seems they've recently added more tracking options, but the one we used is this one: https://github.com/MVIG-SJTU/AlphaPose/tree/master/trackers/PoseFlow#for-any-datasets-general-version

In that example, the `alphapose-results-forvis-tracked.json` is the expected input to our code.

**Comment by Hugstar** [comment]
Thanks. That solved my issue :)

**Comment by hayoyo12** [comment]
@Hugstar Hi, I got same problem with AlphaPose. 
Did you run the scripts/demo_inference.py and then run the trackers/AlphaPose/tracker-general.py to get the right JSON format??
