### ISSUE TITLE
Mismatching keypoints format for my own datasets

### ISSUE THREAD

**Issue by hayoyo12** [google/retiming#3]
Hi, I's trying to run the model with own video.

I just followed the instruction and checked the #2 closed issue to fix the error.
However, I cannot get the keypoints with the specific format. 

First, I tried to use " python scripts/demo_inference.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_1x.yaml --checkpoint pretrained_models/fast_res50_256x192.pth --indir examples/demo/rgb_256/ --outdir examples/res" this to get the alphapose-result.json.

After that I used "python trackers/PoseFlow/tracker-general.py --imgdir examples/demo/rgb_256/ --in_json examples/res/alphapose-results.json --out_json examples/res/alphapose-results-forvis-tracked.json --visdir exa
mples/res/vis/" to get alphapose-results-forvis-tracked.json.

but still the format is as shown as below 
{"png"; [{"keypoints": [...], "scores": #, "idx": #}], "png"; [{"keypoints": [...], "scores": #, "idx": #}], ...}
![error](https://user-images.githubusercontent.com/56079352/116231629-1557b500-a794-11eb-8a10-9bdc0f2ec79c.PNG)

**Comment by erikalu** [comment]
Hi, the format looks correct. Are you getting an error?

**Comment by hayoyo12** [comment]
Hi, Erika

I just reformat the keypoints.json by myself to get the right one.
Sorry for the late response, it takes a while to get the result. I just
want to answer after I get some of results
As I say before, I just used regular alphapose to get the
alphapose-result.json and run the tracker-general.py to get the
alphapose-results-forvis-tracked.json.
However, the format is still shown as "{"png"; [{"keypoints": [...],
"scores": #, "idx": #}], "png"; [{"keypoints": [...], "scores": #, "idx":
#}], ...}"
so, I just reformat by myself..haha :)

Did you run "scripts/demo_inference.py" and then
"trackers/PoseFlow/tracker-general.py"
with images (=video frames)?

**Comment by erikalu** [comment]
Hi, I'm still not sure what you mean because that format actually looks correct to me. Was there an error when you tried using the alphapose-results-forvis-tracked.json file?

And yes, running `scripts/demo_inference.py` and then `trackers/PoseFlow/tracker-general.py` is correct.

**Comment by hayoyo12** [comment]
I mean that the format of the alphapose-results-forvis-tracked.json is should be
"{"png"; [{"score": 0.0, "keypoints": [[#, #, 1.0], [...],...], "idx": #}], ...}"
but I got this:
"{"png"; [{"keypoints": [...],"scores": #, "idx": #}], ... }".

I think the json file is made automatically when I run the trackers/PoseFlow/tracker-general.py.

**Comment by erikalu** [comment]
I just reran the code and the json output worked fine, so I don't think you need to reformat it. The keypoints can be [x1, y1, s1, x2, y2, s2]...

**Comment by hayoyo12** [comment]
Now, I solved the problem!

I used wrong config and pretrained model.
In previous, I just used the halpe26, which is detecting 26 keypoints.
After I used simple baseline model, I just solved the problem. 

Thank you for answering!!
