### ISSUE TITLE
Training visualization 

### ISSUE THREAD

**Issue by hayoyo12** [google/retiming#4]
Hi,

I tried to check the training visualization with Reflection video. 
However, the predicted layers at epoch 100 are look different from the supplementary results. 
Did you change the mask loss/mask threshold/or lambda for mask loss?  

You can check my results below.

Thank you.
![image](https://user-images.githubusercontent.com/56079352/121677830-61b34600-caf1-11eb-9ad5-b7d3c2bb9b32.png)

**Comment by erikalu** [comment]
Hi, that actually looks correct. The reason they are different from the supplementary results is that yours have the detail transfer step applied, whereas the supplementary results show the raw network outputs without the detail transfer.

**Comment by hayoyo12** [comment]
Okay, I still get the rgb at epoch 100 after turn off the detail transfer step, but it looks to learn the outline of people. 
Thank you!
